### ISSUE TITLE
No module named plugins.action

### ISSUE THREAD

**Issue by Wicaeed** [leapfrogonline/ansible-merge-vars#1]
I wrote a simple task to try out the variable merging, and am seeing the following:

```TASK: [system_mount | Merge mount vars] ***************************************
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 348, in run
    if not self._run_play(play):
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 789, in _run_play
    if not self._run_task(play, task, False):
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 497, in _run_task
    results = self._run_task_internal(task, include_failed=include_failed)
  File "/Library/Python/2.7/site-packages/ansible/playbook/__init__.py", line 439, in _run_task_internal
    results = runner.run()
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 1466, in run
    p = utils.plugins.action_loader.get(self.module_name, self)
  File "/Library/Python/2.7/site-packages/ansible/utils/plugins.py", line 218, in get
    self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
  File "/Users/wicaeed/Projects/wicaeed-ansible-playbooks/action_plugins/merge_vars.py", line 8, in <module>
    from ansible.plugins.action import ActionBase
ImportError: No module named plugins.action
```

Are there any minimum requirements for Ansible? I'm currently on 1.9.6

**Comment by fajpunk** [comment]
Sorry, this plugin requires Ansible >= 2.1.0.0.

**Comment by Wicaeed** [comment]
:sadface:
