### ISSUE TITLE
ModuleNotFoundError: No module named 'ansible_merge_vars'

### ISSUE THREAD

**Issue by oldman166234607** [leapfrogonline/ansible-merge-vars#16]
Hello.
I'm having problems using the ansible-merge-vars plugin.
Please, help and thank for your time.

**Describe the Bug**
```
$ pip install ansible_merge_vars

$ python -c "for dist in __import__('pkg_resources').working_set:print dist.project_name.replace('Python', '')"
wsgiref
... skipped
ansible
ansible-vault
ansible-playbook-debugger
ansible-merge-vars
wheel
six
... skipped
cryptography
asn1crypto

$ grep -B1 -A1 action ansible.cfg 
[defaults]
action_plugins = ./plugins/action_plugins

$ mkdir -p ./plugins/action_plugins

$ echo "from ansible_merge_vars import ActionModule" > ./plugins/action_plugins/merge_vars.py

$ ansible-doc -t module -l | grep ansible
add_host        add a host (and alternatively a group) to the ansible-playbook in-memory inventory                                                     
set_stats         Set stats for the current ansible run

$ cat playbook-library/test_merge_vars/test_merge_vars.yaml
- hosts: all
  vars:
    test_01_test__to_merge:
      - 123
      - 456
    test_02_test__to_merge:
      - 234
      - 567

  tasks:
  - name: Merge vars
    merge_vars:
      suffix_to_merge: test__to_merge
      merged_var_name: merged_test_vars
      expected_type: 'list'

$ ansible-playbook playbook-library/test_merge_vars/test_merge_vars.yaml -i inventories/test_merge_vars/inventory 

PLAY [all] **************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************
ok: [192.168.95.2]
ERROR! Unexpected Exception, this is probably a bug: No module named 'ansible_merge_vars'
to see the full traceback, use -vvv

$ ansible-playbook playbook-library/test_merge_vars/test_merge_vars.yaml -i inventories/test_merge_vars/inventory -vvv
ansible-playbook 2.6.2
  config file = /home/oldman/repos/my/ansible.cfg
  configured module search path = ['/home/oldman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/oldman/.local/lib/python3.6/site-packages/ansible
  executable location = /home/oldman/.local/bin/ansible-playbook
  python version = 3.6.6 (default, Sep 12 2018, 18:26:19) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Using /home/oldman/repos/my/ansible.cfg as config file
Parsed /home/oldman/repos/my/inventories/test_merge_vars/inventory inventory source with ini plugin

PLAYBOOK: test_merge_vars.yaml ******************************************************************************************************************************************************************
1 plays in playbook-library/test_merge_vars/test_merge_vars.yaml

PLAY [all] **************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************
task path: /home/oldman/repos/my/playbook-library/test_merge_vars/test_merge_vars.yaml:1
... skipped
ok: [192.168.95.2]
META: ran handlers
ERROR! Unexpected Exception, this is probably a bug: No module named 'ansible_merge_vars'
the full traceback was:

Traceback (most recent call last):
  File "/home/oldman/.local/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/home/oldman/.local/lib/python3.6/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/home/oldman/.local/lib/python3.6/site-packages/ansible/executor/playbook_executor.py", line 159, in run
    result = self._tqm.run(play=play)
  File "/home/oldman/.local/lib/python3.6/site-packages/ansible/executor/task_queue_manager.py", line 289, in run
    play_return = strategy.run(iterator, play_context)
  File "/home/oldman/.local/lib/python3.6/site-packages/ansible/plugins/strategy/linear.py", line 247, in run
    action = action_loader.get(task.action, class_only=True)
  File "/home/oldman/.local/lib/python3.6/site-packages/ansible/plugins/loader.py", line 378, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/home/oldman/.local/lib/python3.6/site-packages/ansible/plugins/loader.py", line 357, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/oldman/repos/my/plugins/action_plugins/merge_vars.py", line 1, in <module>
    from ansible_merge_vars import ActionModule
ModuleNotFoundError: No module named 'ansible_merge_vars'

```

**Ansible Playbook**
```
- hosts: all
  vars:
    test_01_test__to_merge:
      - 123
      - 456
    test_02_test__to_merge:
      - 234
      - 567

  tasks:
  - name: Merge vars
    merge_vars:
      suffix_to_merge: test__to_merge
      merged_var_name: merged_test_vars
      expected_type: 'list'
```

**Environment**
Ansible Version: 2.6.2
Python Version: 2.7.15rc1
Python3 Version: 3.6.6
OS: Ubuntu 18.04.1 LTS

**Comment by oldman166234607** [comment]
Fix this problem:
cp /usr/local/lib/python2.7/dist-packages/merge_vars.py ./plugins/action_plugins/

**Comment by oldman166234607** [comment]
The problem is closed.
Correct solution:
pip3 install ansible_merge_vars
Because my ansible is used by default python3.

**Comment by fajpunk** [comment]
Thanks for the report @oldman166234607, glad you got it figured out.
