### ISSUE TITLE
No longer works with 2.5

### ISSUE THREAD

**Issue by stephen50191** [leapfrogonline/ansible-merge-vars#8]
Traceback:

TASK [merge_vars] ***********************************************************************
task path: /data/test.yml:43
Merging vars in this order: [u'1_attributes__to_merge',u'2_attributes__to_merge']
ERROR! Unexpected Exception, this is probably a bug: update expected at most 1 arguments, got 2
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 159, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 290, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 291, in run
    results += self._wait_on_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 680, in _wait_on_pending_results
    results = self._process_pending_results(iterator)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 117, in inner
    results = func(self, iterator, one_pass=one_pass, max_passes=max_passes)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/__init__.py", line 612, in _process_pending_results
    self._variable_manager.set_host_facts(target_host, result_item['ansible_facts'].copy())
  File "/usr/lib/python2.7/site-packages/ansible/vars/manager.py", line 585, in set_host_facts
    self._fact_cache.update(host.name, facts)
TypeError: update expected at most 1 arguments, got 2

**Comment by fajpunk** [comment]
Hi @stephen50191, thanks for reporting this.  Can you post the playbook and inventory that you used that caused this failure?

**Comment by Victorion** [comment]
Hi @stephen50191 

`Merging vars in this order: [u'1_attributes__to_merge', u'2_attributes__to_merge']`

It works for me with:
- Python 2.7.14
- ansible 2.5.0

and:

```
 - name: Merge variables
   merge_vars:
     suffix_to_merge: attributes__to_merge
     merged_var_name: attribsmerged
     expected_type: 'list'
     dedup: yes
 - debug:
     msg: "{{ attribsmerged }}"
```
```
group_vars/all.yml
 1_attributes__to_merge:
   - test
   - test2
group_vars/test.yml
 2_attributes__to_merge:
   - check
   - ttt
```

**Comment by fajpunk** [comment]
Thanks for verifying @Victorion.  I just added a ton of python/ansible version combinations to the CI job using tox, and all Ansible 2.5.x releases are working with all Python versions.  I'm going to close this @stephen50191, feel free to update and re-open in the future if I missed something.
